//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.18 at 08:17:22 PM EEST 
//


package ua.nure.sereda.SummaryTask3.cards;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Congratulatory"/>
 *     &lt;enumeration value="Advertising"/>
 *     &lt;enumeration value="Normal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeName")
@XmlEnum
public enum TypeName {

    @XmlEnumValue("Congratulatory")
    CONGRATULATORY("Congratulatory"),
    @XmlEnumValue("Advertising")
    ADVERTISING("Advertising"),
    @XmlEnumValue("Normal")
    NORMAL("Normal");
    private final String value;

    TypeName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    /**
     * Determines if a "v" is equal to the string value wrapped by this enum element.
     * @param v string to compare with value.
     * @return value.equals(v)
     */
    public static TypeName fromValue(String v) {
        for (TypeName c: TypeName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
     throw new IllegalArgumentException(v);
    }

}
