//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.18 at 08:17:22 PM EEST 
//


package ua.nure.sereda.SummaryTask3.cards;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OldCard complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OldCard">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Thema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://SummaryTask3.sereda.nure.ua/}Type"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *         &lt;element name="Author" type="{http://www.w3.org/2001/XMLSchema}Name" minOccurs="0"/>
 *         &lt;element name="Valuable" type="{http://SummaryTask3.sereda.nure.ua/}Valuable"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OldCard", propOrder = {
    "thema",
    "type",
    "country",
    "year",
    "author",
    "valuable"
})
public class OldCard {

    @XmlElement(name = "Thema", required = true)
    protected String thema;
    @XmlElement(name = "Type", required = true)
    protected Type type;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "Year", required = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar year;
    @XmlElement(name = "Author")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "Name")
    protected String author;
    @XmlElement(name = "Valuable", required = true)
    @XmlSchemaType(name = "string")
    protected Valuable valuable;


    /**
     * Getter for Theme
     *
     * @return theme
     */
    public String getThema() {
        return thema;
    }

    /**
     * Setter for Theme
     *
     * @param value to set
     */
    public void setThema(String value) {
        this.thema = value;
    }

    /**
     * Getter for Type
     *
     * @return type
     */
    public Type getType() {
        return type;
    }

    /**
     * Setter for Type
     *
     * @param value to set
     */
    public void setType(Type value) {
        this.type = value;
    }

    /**
     * Getter for Country
     *
     * @return country
     */
    public String getCountry() {
        return country;
    }

    /**
     * Setter for Country
     *
     * @param value to set
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Getter for year
     *
     * @return year
     */
    public XMLGregorianCalendar getYear() {
        return year;
    }

    /**
     * Setter for year
     *
     * @param value to set
     */
    public void setYear(XMLGregorianCalendar value) {
        this.year = value;
    }

    /**
     * Getter for Author
     *
     * @return author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Setter for Author
     *
     * @param value to set
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Getter for Valuable
     *
     * @return valuable
     */
    public Valuable getValuable() {
        return valuable;
    }

    /**
     * Setter for Valuable
     *
     * @param value to set
     */
    public void setValuable(Valuable value) {
        this.valuable = value;
    }
}
